server:
  port: 9002  # 端口号

spring:
  application:
    name: nacos-order-feign-consumer  # 应用名称
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # nacos注册中心地址
        ip: 192.168.3.41  # 本机ip

service-url:
  nacos-user-service: http://nacos-payment-provider  # 主要用于代码内获取配置